### ISSUE TITLE
1.5 compatibility

### ISSUE THREAD

**Issue by janat08** [meteor-vue/vue-meteor#114]
https://github.com/meteor/meteor/pull/8327
The new prefetching to improve first load.

**Comment by janat08** [comment]
https://gist.github.com/janat08/7536d755912148820c02553a24ab5dd7
Is likely not a bug, AFAIK findone is a fetch operation, putting findOne within component returns undefined either way.

**Comment by M4v3R** [comment]
Hi @Akryum, will it be hard to implement dynamic imports in meteor-vue-component? I think this feature will really be beneficial for medium and large apps in terms of initial app load time, especially on mobile.

**Comment by janat08** [comment]
#86 is related as it is SSR.

**Comment by gustojs** [comment]
Just for the reference, as there's no hurry. 

At the current moment, with Meteor release `1.5-beta.8`, the following code:
```
    components: {
      test: () => { 
        import('/imports/ui/pages/Test.vue') 
      }
    },
```
results with the following error:
```
   While building for web.browser:
   imports/ui/App.vue:23: [vue-component] Error while compiling in tag
   <script>: Unexpected token, expected { (9:14)
```

**Comment by gustojs** [comment]
For some reason I'm unable to work with local packages, hopefully will resolve that sooner or later, but if anybody wants to give this a try, I'd start with the following steps:

1: Add the Babel's plugin to [vue-component list of npm dependencies](https://github.com/Akryum/vue-meteor/blob/master/packages/vue-component/package.js):
```
"babel-plugin-syntax-dynamic-import"
```
2. Add the following option to Babel's options which are used by [vue-compiler file](https://github.com/Akryum/vue-meteor/blob/master/packages/vue-component/plugin/vue-compiler.js#L56).
```
"plugins": ["transform-vue-jsx", "syntax-dynamic-import"],
```

**Comment by janat08** [comment]
1.5 is out.

**Comment by janat08** [comment]
They also removed buffer polyfill: https://github.com/meteor/meteor/issues/8645

**Comment by Akryum** [comment]
The Buffer error is fixed in vue-component 0.9.1

**Comment by mitar** [comment]
Vue needs Buffer on the client side? That is expensive.

**Comment by Akryum** [comment]
The dev-only HMR system does.

**Comment by mitar** [comment]
OK. :-)

**Comment by Akryum** [comment]
1.5 Code-splitting is now supported in `akryum:vue-component`@0.10.0! Thanks to @nathantreid for the help!

Before (direct import):
![before](https://raw.githubusercontent.com/meteor-vue/vue-meteor/master/withou-async.png)

After (async import):
![after](https://raw.githubusercontent.com/meteor-vue/vue-meteor/master/with-async.png)
