### ISSUE TITLE
Question : ReactContainer equivalent in Vue

### ISSUE THREAD

**Issue by rwatts3** [meteor-vue/vue-meteor#125]
Greetings,

I'm curious if your vue-component package for meteor is the equivalent of the createContainer option for meteor in react.

**Comment by Akryum** [comment]
Not really, it is sort of injection of meteor data at a component level.
However, you can create components that mimic the behavior of `createContainer`.

**Comment by rwatts3** [comment]
So in other words I have to use the meteor Vue component to work with meteor data ? Or is it just sugar.

**Comment by Akryum** [comment]
For meteor data integration, take a look at
https://github.com/Akryum/vue-meteor-tracker

**Comment by ejfrancis** [comment]
@rwatts3 could you close this issue? `vue-meteor-tracker` is the solution for using Meteor data in Vue

**Comment by rwatts3** [comment]
Thank you, My apologize hadn't realized I left it open.
