### ISSUE TITLE
Support vue-meta on SSR

### ISSUE THREAD

**Issue by laosb** [meteor-vue/vue-meteor#149]
... or we can simply get an API for injecting customized HTML?

**Comment by laosb** [comment]
I'm also figuring out how to use vue-ssr. Do I need to use fast-render for subscriptions on SSR? My app is complaining about having no `$subsReady`.

**Comment by Akryum** [comment]
Fastrender is already included and enabled in vue-ssr. I'll take a look at $subsReady
