### ISSUE TITLE
Scoped Templates do not work

### ISSUE THREAD

**Issue by Herteby** [meteor-vue/vue-meteor#191]
If I pass a template into a slot, it works as expected, but as soon as I add scope="test" to the template, it just disappears with no error! I encountered this problem with both [Element](http://element.eleme.io) tables and your Virtual-Scroll. I thought that I must be doing something wrong, but I tried using the most basic example from the Vue guide, and that doesn't work either.

Vue version is 2.3.3

**Comment by thearabbit** [comment]
I have the same problem with `Element`.
But work fine when I use `Vue@2.3.0`.

**Comment by Akryum** [comment]
Do you have any repro to share?

**Comment by Herteby** [comment]
Hmm, now when I tried to create a repro for you, it works again!
Maybe something got fixed in the meantime :slightly_smiling_face:

**Comment by mitar** [comment]
Closing then. :-)

**Comment by green-coder** [comment]
I had the same problem. Updating Meteor to v1.6.0 and updating all my npm fixed the problem.
