### ISSUE TITLE
Error: Can't find npm module 'vue-spinner/src/PulseLoader.vue'.

### ISSUE THREAD

**Issue by nilsi** [meteor-vue/vue-meteor#207]
Im trying to get the [vue-spinner](https://github.com/greyby/vue-spinner) package working in my project. I added the `.vueignore` file and installed `vue-spinner` by `meteor npm install vue-spinner --save`

I then try to use it like this:

```
<template>
    <div class="loading-animation">
        <pulse-loader :loading="true" :color="color" :size="size"></pulse-loader>
    </div>
</template>

<script>

import PulseLoader from 'vue-spinner/src/PulseLoader.vue'

export default {
    components: {
        PulseLoader
    }
};

</script>
```
When trying to run the app Im getting:

```
Error: Can't find npm module 'vue-spinner/src/PulseLoader.vue'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170618-14:30:19.430(9)? (STDERR)     at Object.require (/Users/nilsi/path/.meteor/local/build/programs/server/boot.js:230:17)
W20170618-14:30:19.432(9)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:641:18)
W20170618-14:30:19.434(9)? (STDERR)     at Module.require (packages/modules-runtime.js:234:16)

```

I also tried the same on [vue-meteor-demo](https://github.com/Akryum/vue-meteor-demo) with similar outcome. Not sure if this is a problem related to `meteor` or `meteor-vue`?

**Comment by Akryum** [comment]
Try `import { PulseLoader } from 'vue-spinner/dist/vue-spinner.min.js'`

**Comment by Akryum** [comment]
Also, the new `akryum:vue-component` 0.10.0 package should be able to compile Vue files inside `node_modules`.
