### ISSUE TITLE
Disable HMR

### ISSUE THREAD

**Issue by michalCapo** [meteor-vue/vue-meteor#210]
Hi,
is there a way how to disable HMR reload functionality? Actually its not working for me, and I'm fine with meteor page reloads.

It can be "disabled" by specify HMR_URL to not-existing URL, but its just an ugly workaround.

**Comment by Akryum** [comment]
You can now use `NO_HMR=1`, see https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component#hot-reloading
