### ISSUE TITLE
Include vue compiler for proper errors?

### ISSUE THREAD

**Issue by janat08** [meteor-vue/vue-meteor#211]
I'm told other vue people get compiler that lets them understand errors.

**Comment by Akryum** [comment]
Please explain what your issue is more. :smile:

**Comment by janat08** [comment]
Well so you install vue with npm or webpack that also includes template compiler which identifies actual line and column of error.
https://github.com/vuejs/vue/issues/5948

**Comment by Akryum** [comment]
You can use the full version of vue with the template compiler. Be sure to import this version evrywhere in your code:

```javascript
import Vue from 'vue/dist/vue.min.js'
```

**Comment by janat08** [comment]
I belief official min vue will strip warning.

**Comment by Akryum** [comment]
You can use the normal one then, but beware it will be less performant.

**Comment by janat08** [comment]
Including this in main.js will roughly being screwing with stuff (router/subcache), just importing dist in some component doesn't do much.

**Comment by janat08** [comment]
importing this into main.js at new Vue causes errors, importing this into component alone isn't of much help, same component wide precision.
