### ISSUE TITLE
Adding current component to the router

### ISSUE THREAD

**Issue by mitar** [meteor-vue/vue-meteor#220]
So if I use `vue-router2` package and `RouterFactory`, it seems there is no easy way to add current component to the router. I used this pattern in the past, where everything is in one file, including component registering its route.

I think I could do the following inside component's `<script>`, inside file `/client/Home.vue`:

```js
RouterFactory.configure(factory => {
  // Simple routes
  factory.addRoutes([
    {
      path: '/',
      name: 'home',
      component: '/client/Home.vue'
    },
  ]);
});
```

But then I have to hard-code current filename. If I rename it, I have to also change it inside the file.

Maybe `.vue` components could have a `<route>` section where you have to export a `RouterFactory.configure` callback (still unsure what you would use for `component` value though)? Or maybe there could be a way to reference current component from inside `<script>`?

**Comment by mitar** [comment]
Oh, I could maybe use `Vue.component('Home')` as a value there. It is run after all components are resolved anyway.

**Comment by Akryum** [comment]
I think you should be able to write the component definition in a variable, then use it to configure your route and finally export it.

**Comment by mitar** [comment]
But then that component in a variable will be unnamed (unless I explicitly set the name, but then we are to the square one, how to explicitly set the name to what a filename is).

**Comment by Akryum** [comment]
If you don't set a name, [one should be set](https://github.com/meteor-vue/vue-meteor/blob/master/packages/vue-component/plugin/vue-compiler.js#L675) for you unless it's not working correctly.

**Comment by mitar** [comment]
I thought that will only update the exported component. Does it set directly on the exported variable? Then this could work.

But I am realizing I cannot test it because it does not even work with the code above because of https://github.com/meteor-vue/todomvc/issues/1.

Otherwise, I was thinking that we could augment to `factory.addRoutes` to allow `component` to be a string, and then:
* if it is a string without `/`, it is passed to `Vue.component` directly
* if it is a string with `/`, then we extract the component name from it, in this way one can pass `component: module.id` and get a reference to the current component

**Comment by mitar** [comment]
But yes, assigning a variable, registering a route, and then exporting works well. I just do not know about the component name, but it seems it is not in debugger anyway.

But yes, it works. The name is assigned (I tested it by calling `Vue.component('home') elsewhere).

I will be closing this. This pattern works for me.
