### ISSUE TITLE
Source code change triggers meteor server restart and kills HMR

### ISSUE THREAD

**Issue by gbisheimer** [meteor-vue/vue-meteor#228]
I'm testing meteor-vue integration using the vue-meteor-demo. I wanted to try the HMR feature to get instant updates when working on .vue source files.

After runing the demo app, any update to a `.vue` file triggers a instant update of the displayed component, but also triggers a meteor server restart. HMR feature is lost after this. Further changes to `.vue` files also triggers meteor server restarts, but I have no instant update to the displayed component anymore.

Steps to reproduce:
1. Clone [this](https://github.com/meteor-vue/vue-meteor.git) repo.
2.  Run `meteor server` and open the demo app.
3. Change any file in the `src/imports/ui/` folder, for example, `Notes.vue`
4. UI updates inmediately, and the console log gives:
```
[HMR] Rerendering src/imports/ui/Notes.vue
```
5. After some seconds, I get this on the console:
```
[HMR] Reload request received
[HMR] Client version changed, you may need to reload the page
```

After this, HMR instant updates are lost.

Am I doing something wrong?

**Comment by danielsvane** [comment]
I'm having the same issue, did you find a solution?

**Comment by danielsvane** [comment]
Okay so I figured it out, somewhat. If you disable Meteors auto reloading, the component refreshes (mostly) without issues. Meteors auto reload can be disabled by running with `meteor --once`.

**Comment by gbisheimer** [comment]
Thanks for the tip @danielsvane. Will try it.
