### ISSUE TITLE
How to remove injected Vue-component from Blaze template?

### ISSUE THREAD

**Issue by dolle39** [meteor-vue/vue-meteor#234]
I have a Blaze template as follows:

```
<template name="testtemplate">
   ...
  <schedule></schedule>
  ....
<template>
```

I then initialize a Vue component inside the Blaze template as follows:

```
vm = null;
Template.testtemplate.onRendered(function() {
  vm = new Vue({
    render: h => h(Schedule)
  }).$mount('schedule');

Template.testtemplate.onDestroyed(function () {
  vm.$destroy();
});
```

The problem occurs when I click on some other href of the page which should navigate away from the Vue-component to a pure Blaze-template.  Then the Vue-component does not disappear. I am missing something obviously, but what?
I tried to call the $destroy-event explicitly on the onDestroyed event for the Blaze template but that does not help either.

**Comment by runarberg** [comment]
@dolle39: I don’t know if there is a better way to do this. But I had to manually remove the element after it is destroyed:

```js
Template.testtemplate.onDestroyed(function () {
  vm.$destroy();
  vm.$el.remove();
});
```

**Comment by dolle39** [comment]
Thanks! I found the same solution working as well!
