### ISSUE TITLE
Problem `JSX` on render funciton

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor#235]
I would like to use `JSX` on render function
```js
// Test.vue
<script>
export default {
    name: 'TestComponent',
    render() {
        return (
            <div>Test Component (JSX)</div>
        )
    }
}
</script>
-------------
// Home.vue
<template>
   <test-component></test-component>
</template>

<script>
import TestComponent from './Test.vue'

export default{
        components: {TestComponent},
}
</script>
```
But don't work

**Comment by MaxPleaner** [comment]
would also like to see JSX work with vue-meteor, though I haven't tried it myself yet.

**Comment by Akryum** [comment]
https://github.com/meteor-vue/vue-meteor-demo/commit/ceb3d18ad85919ff99afa7416d3817c0a53a5b3b

**Comment by Akryum** [comment]
Also, [doc](https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component#jsx).
