### ISSUE TITLE
SCSS Import Failed

### ISSUE THREAD

**Issue by hkalex** [meteor-vue/vue-meteor#246]
Hi, I spent a day on this problem and didn't get resolved. :(

I started with `vue-meteor-demo` project. Then run `meteor add akryum:vue-sass` to add the sass package. Then two files were added (copied from **Import** section of http://sass-lang.com/guide )

```
// vue-meteor-demo/src/imports/style/_reset.scss

html,
body,
ul,
ol {
  margin:  0;
  padding: 0;
}
```

```
// vue-meteor-demo/src/imports/style/base.scss

@import 'reset';

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
```

Then at the end of `vue-meteor-demo/src/imports/ui/Home.vue` file, I linked to my `base.scss` file.

```
<style lang='scss' scoped>
@import "./style/base";
</style>
```

But it gave me the following error.

```
[[[[[ ~/Personal/meteor-admin-template/vue-meteor-demo ]]]]]

=> Started proxy.
   [HMR] Dev server listening on port 3003
=> Errors prevented startup:

   While building for web.browser:
   src/imports/ui/Home.vue:1: [vue-component] Error while compiling in tag <style> using lang scss Unknown import (file not
   found): reset

   While building for os.osx.x86_64:
   src/imports/ui/Home.vue:1: [vue-component] Error while compiling in tag <style> using lang scss Unknown import (file not
   found): reset

=> Your application has errors. Waiting for file change.
=> Started MongoDB.

```

I also tried another way to link `base.scss` but still had the same error.

```
<style lang='scss' src="./style/base.scss" scoped></style>
```

**Comment by Akryum** [comment]
Check the path of you sass file. It should be `../style/base`.

**Comment by hkalex** [comment]
Sorry for my typo on this post.

I checked my solution and all paths are correct. And here is the screenshot.

![image](https://user-images.githubusercontent.com/1491345/29739543-a41c5c28-8a83-11e7-85bd-f79156caffb8.png)

The error message is talking about cannot find "reset" file.

**Comment by Toomean** [comment]
Having the same error

**Comment by marvinside** [comment]
I just checked out meteor-vue and also are having problems with scss and sub-imports.
In an normal Vue-Project, i was using a config for the css loader to tell it where to look for files:
```js
module.exports = {
	baseUrl: "/",
	css: {
	  loaderOptions: {
		sass: {
		  includePaths: [path.resolve(__dirname,'node_modules')],
		  importExtensions: ['.scss', '.css'],
		},
	  },
	},
  };
```

As you can see, the folder 'node_modules' is added to the include-paths.

I suggest an option in package.json to add new import paths.
The options has to be fetched and added to the array here: https://github.com/meteor-vue/vue-meteor/blob/65abcc3155377afd53b22d081599cef0a19baa37/packages/vue-sass/vue-sass.js#L36

I'll now check if i can manage to get this to work and create an pull-request if possible. (not much experience with meteor packages...)

In another Project (just meteor) i also had problems importing `@material` Scss files, so i modified my sass.render code a bit:

```js
importer: (url: string, _prev: string, done: (data: { file: string }) => void): void => {
	if (url.startsWith('@material/')) {
		// remap @material scss files.
		const cwd: string = process.cwd();
		const path: string = `${cwd}/../web.browser/app/scss/${url}`;
		lastPath = path;
		done({ file: path });
	} else {
		done({ file: url });
	}
},
```

This is basically doing the same by detecting @material imports and changing the path to import.
