### ISSUE TITLE
Excuse me, don't know font icon of `Element UI` when refresh page (localhost:3000/....)!

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor#247]
I use `Element UI`, and I copy `fonts folder` to `/public`.
- It works fine on home page (localhost:3000)
- Don't work on `localhost:300/..../` (not home page), when refresh page

**Comment by thearabbit** [comment]
Now I found the problem
- `@font-face` path of `Elemnet` ->`fonts/.....`
- But `Meteor Guide` -> `/fonts/....` of `public folder`.

**Comment by x007xyz** [comment]
> Now I found the problem
> 
> * `@font-face` path of `Elemnet` ->`fonts/.....`
> * But `Meteor Guide` -> `/fonts/....` of `public folder`.

Hi,how to solve this problem?

**Comment by thearabbit** [comment]
- Copy `fonts` to `/public/fonts`
- Startup font with 
```
@font-face {
  font-family: element-icons;
  src: url(/fonts/element-icons.woff) format('woff'),
    url(/fonts/element-icons.ttf) format('truetype');
  font-weight: 400;
  font-style: normal;
}
```

**Comment by x007xyz** [comment]
> * Copy `fonts` to `/public/fonts`
> * Startup font with
> 
> ```
> @font-face {
>   font-family: element-icons;
>   src: url(/fonts/element-icons.woff) format('woff'),
>     url(/fonts/element-icons.ttf) format('truetype');
>   font-weight: 400;
>   font-style: normal;
> }
> ```

Thank you!
