### ISSUE TITLE
Can't create vue components

### ISSUE THREAD

**Issue by ShaktiDas** [meteor-vue/vue-meteor#250]
I'm trying to implement the vue component according to this doc:
https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component
But it's not working. Is there any live example?

**Comment by Akryum** [comment]
Did you try [the demo project](https://github.com/meteor-vue/vue-meteor-demo)?

**Comment by ShaktiDas** [comment]
Thanks for your reply. It's working perfectly when using your demo project.  I've created multiple components in your demo project.
But the same code is not working in my project.
![image](https://user-images.githubusercontent.com/1048619/30374545-233f711c-98a7-11e7-9e9b-737802518ed0.png)

BTW. I'm using this in my project:
import {Vue} from 'meteor/akryum:vue';

Could you please advice what I'm missing there?

**Comment by ShaktiDas** [comment]
Not sure what was the wrong. But it's OK now!
