### ISSUE TITLE
TabPane: Select and DatePicker partially hidden 

### ISSUE THREAD

**Issue by CassianoViana** [meteor-vue/vue-meteor#255]
I have a form with a DatePicker inside Form into a TabPane.
As you can see the bottom of the DatePicker is hidden by the foreground.
The same occurs with select (I have the options 1,2,3 in the example).

![screenshot from 2017-09-27 09-31-57](https://user-images.githubusercontent.com/6260991/30913541-f82f9c7a-a366-11e7-9492-33e920d52645.png)

![screenshot from 2017-09-27 09-37-11](https://user-images.githubusercontent.com/6260991/30913692-7bbeea1e-a367-11e7-95d5-478942a0728e.png)

The fullscreen:
![screenshot from 2017-09-27 09-45-21](https://user-images.githubusercontent.com/6260991/30914143-f271e3c2-a368-11e7-9281-e557ef4eec12.png)

My code is:
`<Tabs value="termosUso">
			<TabPane label="Detalhes" name="detalhes">
				<CursoFormDetalhes></CursoFormDetalhes>		
			</TabPane>
                      ...other TabPanes
		</Tabs>`

In CursoFormDetalhes i have a Form with rows and the FormIten with de Select/DatePicker..

I'll appreciate any help

**Comment by Akryum** [comment]
Thanks for submitting an issue, but it doesn't seem to be related to the Vue + Meteor integration and rather issues with those components themselves. I suggest reaching out the creator of these components or ask your questions on a more appropriate place like the Vue forums or discord.

**Comment by CassianoViana** [comment]
Sorry
