### ISSUE TITLE
Data is not reactive...

### ISSUE THREAD

**Issue by iojanis** [meteor-vue/vue-meteor#260]
Hello,

don't know what's wrong but my data is not reactive and only updates when I refresh the page. 
I'm using the vue-meteor-demo and implemented my own collection which is filled with data by a function running on the server.

**Comment by Akryum** [comment]
Do you have a repro?

**Comment by iojanis** [comment]
I'm sorry for the inconvenience, I missed the freeze setting... Working just fine now. You did some great work, thanks!
