### ISSUE TITLE
Hot reloading doesn't seem to work for me.

### ISSUE THREAD

**Issue by trusktr** [meteor-vue/vue-meteor#294]
I have a mostly React based app at the moment, then inside the React app I've mounted a Vue component like this:

```js
import Foo from './Foo.vue'
(new (Vue.extend(Foo))).$mount(this.refs.tmp)
```

Then, when I update only code inside of `Foo.vue`, the whole application reloads. How do I prevent that from happening?

What are the requirements for Hot Loading to work, the README doesn't say.

**Comment by trusktr** [comment]
I also tried making a wrapper component that looks like this:

```vue
<template>
    <the-actual-component></the-actual-component>
</template>

<script>
    import TheActualComponent from './the-actual-component.vue'

    export default {
        components: { TheActualComponent },
    }
</script>
```

so that the wrapper is manually mounted inside the React component with `$mount`, and the wrapper renders the actual component that I want to show inside of its template.

Yet, if I change only the code in the-actual-component (not in the React component and not in the wrapper), the whole entire application still reloads.

How do we make it work?

**Comment by trusktr** [comment]
A reproduction is here: https://github.com/trusktr/trusktr.io/tree/ce403c126c169a0a038918721dc120c5660a66eb

(at that commit, but probably the same problem still persists on master)

To run:

```sh
cd meteor-app
npm i
meteor
```

then visit http://localhost:3000/earth to see the demo that loads up a Vue-based component. If you edit the file `meteor-app/client/imports/apps/earth.vue` it will cause a full app reload, which I was hoping to avoid.

**Comment by dtruel** [comment]
I have this same issue.

**Comment by Akryum** [comment]
It should be fixed in the upcoming release.
