### ISSUE TITLE
Vue-component syntax error in IE

### ISSUE THREAD

**Issue by SnooHD** [meteor-vue/vue-meteor#306]
In IE11 i get the following syntax error:
``
SCRIPT1002: Syntax error
akryum_vue-component-dev-client.js (8214,1)
``
The code that is on this location:
``
class WebSocket extends EventEmitter
``
Is this an issue with babel? I am using meteor 1.6.1 with `@babel/runtime` installed.

**Comment by wildhart** [comment]
Same here, on the same `class WetbSocket...` line.  With Meteor 1.8.0.2 and `@babel/runtime` 7.1.2.

I don't get it when compiling with the `--production` flag though, only development.

**Comment by GeoffreyBooth** [comment]
`vue-component-dev-client` needs to be build with transpilation. This is the error in IE11:

![image](https://user-images.githubusercontent.com/456802/56311044-f1bbf780-6101-11e9-96d0-ebe529eef766.png)

from here:

![image](https://user-images.githubusercontent.com/456802/56311076-04363100-6102-11e9-9365-775ad91f3ea8.png)

IE11 doesn’t support the `class` keyword, so including `WebSocket.js` without transpilation will cause this error in IE11. The solution would be to have `vue-component-dev-client` be fully transpiled by Babel.

It would be nice to get this fixed, as it would be much easier to debug IE11 issues if `vue-component` could run in IE11 in development mode.
