### ISSUE TITLE
Getting a strange PostCSS error after updating Meteor

### ISSUE THREAD

**Issue by eybarta** [meteor-vue/vue-meteor#312]
Hey, thx for your great work.

After updating Meteor to last version + packages..
I'm getting this error running locally which strangely goes away
after I save a file and HR kicks in.. It's more bothersome
because sometimes my deployment breaks because of the same error.
![image](https://user-images.githubusercontent.com/12781988/38491975-2f8d3466-3bf6-11e8-9b72-e5c093f91137.png)

My package.json settings:
```
"postcss": {
    "plugins": {
      "autoprefixer": {
        "browsers": [
          "last 2 versions"
        ]
      },
      "postcss-responsive-type": {},
      "lost": {}
    }
  }
```
and I have those libs installed..

Please let me know if you need more information and how to solve this issue.

Thanks again

**Comment by mitar** [comment]
Same here. I am getting this error on clean install, but not in my existing development environment. I could not yet find a difference.

**Comment by mitar** [comment]
I think the issue is that this package integrates PostCSS for processing styles inside components. And has a hard-coded set of NPM packages available to that install of PostCSS. And then the issue is that this internal PostCSS is picking external PostCSS configuration, but cannot find a plugin among internal NPM packages.

Probably this could be solved by making PostCSS a peer-dependency?

**Comment by mitar** [comment]
I made this pull request which addresses this for me: https://github.com/juliancwirko/meteor-postcss/pull/32

Then I create `.postcssrc.js` file in the root of the app with:

```js
module.exports = (ctx) => {
  if (ctx.meteor) {
    const config = {
      plugins: {
        'postcss-easy-import': {},
      },
    };

    if (ctx.env === 'production') {
      // "autoprefixer" is reported to be slow,
      // so we use it only in production.
      config.plugins.autoprefixer = {
        browsers: [
          'last 2 versions',
        ],
      };
    }

    return config;
  }
  else {
    return {};
  }
};
```

**Comment by mitar** [comment]
I made #317 to address this.
