### ISSUE TITLE
Should use Meteor 1.7 or 1.6???

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor#323]
Now Meteor release 1.7.
Should use old (1.6) or new (1.7)?

**Comment by bartmichu** [comment]
I have updated my project about a week ago and didn't notice any problems so far.

**Comment by thearabbit** [comment]
waiting recommendation...

**Comment by thearabbit** [comment]
Now I try to updated to `Meteor 1.7`, but have problem with `fourseven:scss`

**Comment by bartmichu** [comment]
@thearabbit did you follow the instructions from [https://atmospherejs.com/fourseven/scss]() page?

**Comment by thearabbit** [comment]
I found, but not clear
```
Note that Meteor 1.7 introduced a change so that files in node_modules aren't automatically compiled any more. This requires you to add a symlink inside the imports directory to the pacakge in order for compilation to work. E.g.

meteor npm install the-package
cd imports
ln -s ../node_modules/the-package .
```

**Comment by thearabbit** [comment]
Could explain?

**Comment by MichaelJCole** [comment]
The Guide project could also use an update:  https://github.com/meteor-vue/guide/issues/6

**Comment by thearabbit** [comment]
Very thanks
