### ISSUE TITLE
vue-component not working?

### ISSUE THREAD

**Issue by glor** [meteor-vue/vue-meteor#324]
The console sais `[HMR] Vue component hot reload shim applied.` so vue-components seams to be loaded. I can also access imported vue components (as objects). But the text does not change from test to example. I also never get an `alert()`. It works in a plain vue setup (vue init webpack-simple)
main.js:
```javascript
import Vue from 'vue'
import App from './App'

new Vue({
    el: "#app",
    render: h => h( App ),
});
```
main.html:
```javascript
<body>
<div id="app">test</div>
</body>
```
App.vue:
```javascript
<template>
    <div id="app">
        content
    </div>
</template>

<script>
    export default {
        name: 'app',
        data: function () {
            return {
                msg: 'Welcome to Your Vue.js App',
                whatever: alert()
            }
        }
    }
</script>

<style>
</style>
```

**Comment by vermadivyanshu** [comment]
you see that your main and app.vue both have an id app, you might want to use a different id, that might be causing some problem. You cannot see an alert because you have not used whatever inside the template. I have not tried your code yet.

**Comment by Akryum** [comment]
It should be fixed in the upcoming release.
