### ISSUE TITLE
error on fast-rendering path

### ISSUE THREAD

**Issue by mehrdadphp** [meteor-vue/vue-meteor#328]
# Hi

### I run the project, when I load the pages in the terminal, I encounter this error

```` 
Meteor server restarted                    
W20180627-09:59:46.709(4.5)? (STDERR) error on fast-rendering path: /property-list ; error: TypeError: Cannot read property '_injectPayload' of undefined
W20180627-09:59:46.709(4.5)? (STDERR)     at Object.getData (packages/staringatlights:inject-data/lib/server.js:63:18)
W20180627-09:59:46.710(4.5)? (STDERR)     at packages/staringatlights_fast-render.js:212:38
W20180627-09:59:46.710(4.5)? (STDERR)     at packages/staringatlights_fast-render.js:288:7
I20180627-09:59:46.743(4.5)? [SSR] Data prefetch: 23ms

**Comment by lobosan** [comment]
Same here

**Comment by nisaus** [comment]
I'm getting this as well. Anyone knows what's up?

**Comment by mritunjaybchurunway** [comment]
I am getting the same 
`error on fast-rendering path: / ; error: TypeError: Cannot read property '_injectPayload'
 of undefined
W20181024-16:57:08.969(7)? (STDERR)     at Object.getData (packages/staringatlights:inject-data/lib/server.js:63:18)
W20181024-16:57:08.970(7)? (STDERR)     at packages\staringatlights_fast-render.js:212:38
W20181024-16:57:08.970(7)? (STDERR)     at packages\staringatlights_fast-render.js:288:7`

Any help

**Comment by erwzqsdsdsf** [comment]
I am getgting the same error

**Comment by yosiah** [comment]
same error, too.

`=> Started proxy.
=> [HMR] Dev server listening on port 4003.
=> Meteor 1.8 is available. Update this project with 'meteor update'.
=> Started MongoDB.
I20181103-17:52:22.570(9)? tracker installed
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

W20181103-17:52:45.417(9)? (STDERR) error on fast-rendering path: / ; error: TypeError: Cannot read property '_injectPayload' of undefined
W20181103-17:52:45.421(9)? (STDERR)     at Object.getData (packages/staringatlights:inject-data/lib/server.js:63:18)
W20181103-17:52:45.421(9)? (STDERR)     at packages\staringatlights_fast-render.js:212:38
W20181103-17:52:45.422(9)? (STDERR)     at packages\staringatlights_fast-render.js:288:7
I20181103-17:52:45.450(9)? [SSR] Data prefetch: 20ms`

**Comment by bennyschudel** [comment]
anyone has a solution for this?
