### ISSUE TITLE
Meteor 1.8 cannot find module @babel\runtime\helpers\builtin\interopRequireDefault

### ISSUE THREAD

**Issue by ghost** [meteor-vue/vue-meteor#334]
With Meteor 1.8 seems like akryum:vue-component is having an issiue . 

While loading plugin vue-component from package akryum:vue-component:
   module.js:547:15: Cannot find module
   'C:\Users\Salih\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\\@babel\runtime\helpers\builtin\interopRequireDefault'

This is the error when i run 'meteor' command with my newly created meteor 1.8. I only added  akryum:vue-component so far.

**Comment by bartmichu** [comment]
I have the same problem on Windows machine, both after starting a new 1.8 project and after upgrading existing one (which was working fine with previous meteor version).
No problems on Ubuntu machine with the same repository.

**Comment by salihbaki** [comment]
@bartmichu I will try at ubuntu. Meteor gives me hard time at windows :/

**Comment by kerf007** [comment]
I have the same problem on windows machine and no problem on mac. Help, please :)

**Comment by piotrek-horodenski** [comment]
I have the same issue, please help.

**Comment by yosiah** [comment]
only, the same problem on Windows machine, 
No problems on Ubuntu machine with the same repository.

**Comment by pkl6612** [comment]
I have the same issue

**Comment by ThaumRystra** [comment]
This is still an issue in Meteor 1.8.0.1

**Comment by haomasoma** [comment]
Just copy all files from the folder one level up of that 'builtin', worked for me

**Comment by red-meadow** [comment]
I removed both `@babel/runtime` and `akryum:vue-component` and then installed again. It helped.

**Comment by Akryum** [comment]
Installing `@babel/runtime` and running `meteor reset` should fix it.
