### ISSUE TITLE
Could you double-check the Vue+Meteor documentation?

### ISSUE THREAD

**Issue by MichaelJCole** [meteor-vue/vue-meteor#340]
Hi, I made a bunch of changes to the Vue+Meteor documentation.

Could you please take a look and PR where I made mistakes?  

The page quickly builds Vue+Meteor app, but I couldn't get the SSR stuff working with it.

https://guide.meteor.com/vue.html
https://github.com/meteor/guide/pull/931

Thanks!  I'm stoked about Meteor and Vue :-)

**Comment by chris-visser** [comment]
I've just made another PR related to SSR. It might fix your issue. SSR works on my side. Which scenario are you trying? The one with async data or the simple one?

**Comment by MichaelJCole** [comment]
@chris-visser awesome!  I remember the SSR stuff was theoretical and not tied to the example.  Looking forward to it!

**Comment by chris-visser** [comment]
I saw that akryum has merged it. You might want to give it a try. If it doesnt work, can you share your code?

Also I have a boilerplate that does work with SSR. You might want to compare it with yours:

https://github.com/chris-visser/meteor-vue-boilerplate

**Comment by MichaelJCole** [comment]
Awesome!  You might want to make that into the Meteor Tutorial - it could really use some help!

**Comment by MichaelJCole** [comment]
Hey Chris, I'm boarding a plane.  In my repos is a Todo repo.  There is an
issue w/ reactivity though...

**Comment by chris-visser** [comment]
Will check it out. Thanks for notify
