### ISSUE TITLE
error caught on publication

### ISSUE THREAD

**Issue by mehrdadphp** [meteor-vue/vue-meteor#344]
hi guys

i clone project vue + meteor demo example meteor 1.8 .

i run : 

```
meteor npm  install
```

```
meteor
```

**But the terminal has the following error :** 
‍‍
`
error caught on publication:  notes :  Can't publish a cursor from a collection without a name.
`

That's why it can be ? @Akryum

**Comment by jamgold** [comment]
Even though everything works as I expect it to, I see the same error message. But I am not even sure it is coming from this module. I notice that the log id is different from console.log in my own app
```
=> Meteor server restarted
I20190406-12:29:50.662(-7)? Sending non-Meteor data to Vue component
W20190406-12:29:50.673(-7)? (STDERR) error caught on publication:  Time :  Can't publish a cursor from a collection without a name.
```

**Comment by promentol** [comment]
Any solution to this????

**Comment by mehrdadphp** [comment]
@promentol new version is a problem, I use version 1.7

**Comment by welkinwong** [comment]
same, i use version 1.8.1, how to fix this problem?
