### ISSUE TITLE
Unexpected HMR behavior

### ISSUE THREAD

**Issue by DavidReinberger** [meteor-vue/vue-meteor#348]
Hey everyone, I'm trying to setup vue with meteor, unfortunately I can't get the same developer UX like with vue-cli or webpack. Meteor reloads the page most of the time instead of replacing the module. See this repo https://github.com/DavidReinberger/vue-meteor-hmr-test.

Try to edit any of the vue files inside the import directory, after first edit, most of the time, HMR kicks in properly and reloads the module, after editing it for the second time, it reloads the whole app :/

Any idea why?

**Comment by marvinside** [comment]
Having the same Problems.

As a Workaround you can Fork the Package [vue-component-dev-client](https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component-dev-client), symlink it to /packages in your Meteor project folder (overrides Repository, Meteor will then use the local version).

Then add `_suppressNextReload = true;` after [Line 201](https://github.com/meteor-vue/vue-meteor/blob/master/packages/vue-component-dev-client/client/dev-client.js#L201) in the dev-client.js
(Or checkout https://github.com/meteor-vue/vue-meteor/pull/347)


Also you might have to do this: (Not in PR currently)
```js
setTimeout(()=>{
  _suppressNextReload = true;
}, 300);
```
As your Project grows bigger, there will be some delay on some stuff. So you have to supress again after a short time.
I have not investigated why this is needed a second time. Feel free to help.

**Comment by DavidReinberger** [comment]
Hi @marvinside thanks for the comment it prompted me to investigate further! AAAAND I've found a solution to our problem. Nevertheless I'm not 100% sure about the implications.

Basically the debounce in `vue-component/vue-compiler.js` is too long for the compiler to pickup fast changes and secondly, meteor reloads every time simply because the compiler adds `.js` extension to every `.vue` file, which is afterwards picked up by the meteor `ecmascript` package thus reloading the app.

I'll be happy to submit a PR to this repo. @mitar could you please shed a little bit of light, why the debounces and `.js` extension? Thanks!

**Comment by mitar** [comment]
I am no familiar with this code.

**Comment by DavidReinberger** [comment]
Ah sorry, saw you as the only "people" [here](https://github.com/meteor-vue), should have tagged @Akryum

**Comment by DavidReinberger** [comment]
Alright after further observations:
**If you are not using client/server folder in your imports folder** (tested on custom package)
1. the server is going to get reloaded which gets you a very unexpected behavior with the debounce
2. slow reloads

**If you are using client folder in your imports folder** (tested on vanilla package)
1. The App only reloads the client
2. The app reloads after any change (because FE migrations)
3. The 'changed' event is sent multiple times - thus the debounces i guess?

**Comment by mathieustan** [comment]
`Reload._onMigrate(() => null);` doesn't refresh JS in vue component :(

**Comment by Akryum** [comment]
It should be better with latest release.
