### ISSUE TITLE
Modification on imported files in a Vue component "style" tag don't trigger a reload

### ISSUE THREAD

**Issue by Neijin** [meteor-vue/vue-meteor#349]
Hi everyone !
It seems like Stylus imported files from the "style" tag of a Vue component don't trigger rebuilding and hot-reloading anymore.

**button.vue**
`<style lang="stylus" scoped> @import "./button.import" </style>`

**button.import.styl**
`.button { color red cursor pointer }`

Modifications of the button.import.styl file doesn't do anything.

**Comment by Neijin** [comment]
Found it.

In Stylus we are used to to @import our style files by omitting the ".styl" extension at the end.
_@import './index.import'_

In vue-meteor for a single component, you have to add the ".styl" back to allow your imported Stylus files to be watched and reloaded when a change occur.
_**@import './index.import.styl'**_

**Comment by alejandroiglesias** [comment]
This is also happening to me with Sass (SCSS syntax). Everything was working fine until all of a sudden, SCSS modifications stopped triggering a reload, and some styles failed to be applied, specifically if not imported with the `.scss` extension. Hopefully, I found this issue and as @Neijin suggests, I'm experimenting with adding extensions. I hope that keeps working and I don't see random behavior, will see.

**Comment by Neijin** [comment]
@alejandroiglesias Adding extensions didn't fix it for me. It might be linked to daisy-chained _imports_ but I'm still not sure since the errors seem random. Are your on Windows ?

Put your entire style into the Vue component file should work fine, but this is not a solution for me.

**Comment by alejandroiglesias** [comment]
@Neijin I'm on macOS. Adding the extension to all the Sass files did the trick. They compile correctly and I get updates as I code. The challenging part of the debugging was that there were 2 issues: 1) Not compiling files included without extension, and 2) not updating the page on reload. So I didn't get a correct update when I removed the extensions from the imports (a common practice when I worked with pure/node-sass), and when I went many commits back using git bisect, the code correctly had the extension but the page didn't update on reloading, so I still saw the unstyled component.

Anyhow, seems solved on my end but worse for your case on Stylus files and/or Windows environment.

**Comment by alejandroiglesias** [comment]
Another issue I saw today is that the build/reload does not happen if I have a component with styles in a `<style>` tag and remove the whole tag altogether. I have to remove only the rules and leave the empty `<style>` for the build to happen.

**Comment by alejandroiglesias** [comment]
@Neijin are daisy-chained imports also using an extension? It may be that if you import a library and the library imports other files without an extension it also breaks?

**Comment by alejandroiglesias** [comment]
Unfortunately, I still see that sometimes it randomly stops compiling my `main.scss` file imported in my `App.vue` component.

**Comment by Neijin** [comment]
@alejandroiglesias I have exactly the same problem. None of what I tested so far worked for long.

**Comment by Neijin** [comment]
@alejandroiglesias Daisy-chained imports with and without extension don't work reliably. Same issue with direct imports from the Vue Single File Component.

**Comment by alejandroiglesias** [comment]
@Neijin have you found some workaround?

@Akryum I'm trying to make style changes in my application and this is becoming very annoying. Whenever I make changes to a file that's imported inside the component `<style>` tag (in my case: `<style lang="scss">`), the app doesn't update, even if I manually reload the browser (ie, doesn't recompile). What's most strange, if I comment out the import, save the file, and then uncomment, I get the new styles for a second, and then it goes back to the previous state (ie, a previous cache?).
Can you please give us a hint on how to solve it?
Thanks.

**Comment by Neijin** [comment]
@alejandroiglesias For now I just switch between **import** and **switch** for my stylus files inside the _style_ part of my Vue component and then I saved. Pretty much like you. If it doesn't work (or sometimes when the CSS get rollbacked to a previous version), I have to make a meteor reset.

**Comment by alejandroiglesias** [comment]
@Neijin I see. It's the same for me, but sometimes that doesn't work and I was wondering how to address that. By "meteor reset" you mean stop and restart the server or actually run `meteor reset`?

**Comment by Neijin** [comment]
@alejandroiglesias Actually run the ```meteor reset``` command.

**Comment by igal1c0de4n** [comment]
Also bumping into this.

Can someone from the Meteor-Vue team share their insights re this issue?
@mitar @Akryum

**Comment by Neijin** [comment]
@alejandroiglesias @igal1c0de4n So. I found a "workaround" that seems to work for me now. I import all my shared-between-components Stylus files and I put the specific component CSS code directly inside the <style> tag.

`<style lang = "stylus" scoped>
  @require "~imports/common/client/style/constants/example1.import.styl"
  @require "~imports/common/client/style/constants/example2.import.styl"

  #my-component
  {
    text-align center
    background-color THEME_COLOR_PRIMARY
  }
</style>
`

**Reloads seems to work fine when you have import/require and actual CSS code inside your <style> tag.**

**Comment by alejandroiglesias** [comment]
@Neijin yes I'm already aware of that. Most of the styles are residing in components, but the problem for me is global styles.

**Comment by Neijin** [comment]
@alejandroiglesias I didn't experienced any issues in that specific case for now. I'll let you know.

**Comment by alejandroiglesias** [comment]
@Neijin how are you importing the styles?

**Comment by Akryum** [comment]
It's fixed in the latest version of `vue-stylus`.
