### ISSUE TITLE
How to change the HMR domain (the "origin")?

### ISSUE THREAD

**Issue by trusktr** [meteor-vue/vue-meteor#372]
I'm running my dev server online, and it detect the HMR domain to be my server's IP, like `34.234.56.4:3003`, and it tries to access `https://34.234.56.4:3003` at runtime, which is not allowed by my server.

How I can I specify for it to use a certain domain? F.e., I'd like it to use `dev.example.com:3003` so that at runtime it will access `https://dev.example.com:3003` without problems.

Right now, I see errors like this in Chrome devtools:

```
https://34.234.56.4:3003/socket.io/?EIO=3&transport=polling&t=MrMerUL&b64=1 net::ERR_CONNECTION_REFUSED
```

because the server doesn't not allow connections like that.

**Comment by trusktr** [comment]
It's hard to come up with search terms to find the right search results.

Turns out these are my two exact issues, the second one due to the first:

1. https://github.com/meteor-vue/vue-meteor/issues/156
2. https://github.com/meteor-vue/vue-meteor/issues/107

I'll close this, as I think HMR_URL will do the trick.

**Comment by trusktr** [comment]
Alright, I can use `HMR_URL` to specify the domain, but how do I tell it not to use a port? I need HMR to just access a URL with only domain, without the port.

**Comment by trusktr** [comment]
Dang, looks like there's no way, the code does:

```js
const PORT = parseInt(process.env.HMR_PORT) || parseInt(process.env.VUE_DEV_SERVER_PORT) || getMeteorPort() || 3003
```

which forces the port to exist.

**Comment by trusktr** [comment]
For reference, that code prevents from doing this:

```js
HMR_URL=dev-server.example.io HMR_PORT="" meteor -p 2345
```

because the empty string returns falsey in the code.

**Comment by trusktr** [comment]
So, a port is still needed for dev-server, just that the client should not try to use a port. It'd be nice to have a way to tell only the client code not to use a port.

**Comment by Akryum** [comment]
There always is a port when you use the network on a computer. By default, using http the port is 80 and https it's 443. The list of commonly used ports [on wikipedia](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers).
