### ISSUE TITLE
Meteor 1.8.2 lots of console logs "module Module {id: "/imports/ui/..."

### ISSUE THREAD

**Issue by wildhart** [meteor-vue/vue-meteor#382]
Since upgrading to Meteor 1.8.2 I'm getting a browser console log message whenever a Vue file is imported:

![Screenshot from 2019-12-11 03-37-02](https://user-images.githubusercontent.com/12505024/70538782-8ad6db80-1bc7-11ea-9e92-eb61bb8b0422.png)

Looks like it's coming from this line: https://github.com/meteor-vue/vue-meteor/blob/6ef113739751c024f02bf67c5c71c6c5da094ae6/packages/vue-component/plugin/tag-handler.js#L182

Where is `module.watch` coming from and how do I set it to true?

Should that `console.log` still be in the code?

**Comment by mathieustan** [comment]
Wow. I just found this code too. It s weird because this code is there since two years already. ‘module.watch’ changed recently ? I hope we can set an option to enable/disable this.

**Comment by wildhart** [comment]
@akanix42 added this `console.log` in this commit: https://github.com/meteor-vue/vue-meteor/commit/53deae6a9bb4fb3da6a1fdbd7a6593d97b04af30.  @akanix42, can you explain where `module.watch` comes from what what we can do about this?  Are you happy for me to submit a PR to remove the `console.log`, or do you want to?

**Comment by mathieustan** [comment]
@Akryum do you have any idea ?

**Comment by akanix42** [comment]
Here's the relevant PR: #297. I don't recall the specifics of `module.watch`, but it's a Meteor core thing. As for the log, yes please remove that. It's leftover from debugging. :woman_facepalming:

**Comment by wildhart** [comment]
Done. PR #383

**Comment by jamgold** [comment]
I upgraded to the latest version and the application crashes now with 
```
[vue-component] Error while compiling in tag <script>: Unknown option: .module. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```
