### ISSUE TITLE
Better Vue scheme with Meteor

### ISSUE THREAD

**Issue by macarthuror** [meteor-vue/vue-meteor#388]
Hello guys 🖖,

I´m new using Meteor with Vue and I wondering to know what's the best scheme to use it.

Could anyone can show me how is handling this in your projects ?

Thanks

**Comment by mullojo** [comment]
Hi @macarthuror, I could probably help you out, you should probably start here: https://guide.meteor.com/vue.html

You can find me on the Meteor Community Slack: https://meteor-community.slack.com ... there is a #vue channel on there that you should join.  

Enjoy Meteor + Vue, it's the best combo in my book!

**Comment by macarthuror** [comment]
Thanks 😁

**Comment by nosizejosh** [comment]
I am facing similar blicking issue with the latest version
https://github.com/meteor-vue/vue-meteor-demo/issues/35
https://github.com/meteor-vue/vue-meteor/issues/399
